version: "3"
networks:
  gamma:

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user # These should all be changed
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - gamma

  backend:
    # ./gradlew bootBuildImage
    image: gamma:1.0.0-SNAPSHOT
    environment:
      # Default admin user name = admin
      # Default admin password  = password

      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres

      REDIS_HOST: redis
      REDIS_PASSWORD: ""
      REDIS_PORT: 6379

      GOTIFY_KEY: "123abc"
      GOTIFY_URL: http://gotify:8080/mail

      SERVER_PORT: 8081

      COOKIE_DOMAIN: gamma
      IS_MOCKING_CLIENT: "true"
      BASE_URI: "http://gamma:8081"
    depends_on:
      - redis
      - db
    networks:
      - gamma
    ports:
      - 8080:8081

  redis:
    image: redis
    networks:
      - gamma

  gotify:
    image: cthit/gotify
    networks:
      - gamma
    environment:
      GOTIFY_PRE-SHARED-KEY: 123abc
      GOTIFY_MOCK-MODE: "true"
