version: "3"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  redis:
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379

  gotify:
    image: cthit/gotify
    environment:
      GOTIFY_PRE-SHARED-KEY: 123abc
      GOTIFY_MOCK-MODE: "true"
    ports:
      - 8080:7000
