version: "3"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    network_mode: host

  redis:
    image: redis:5.0
    restart: always
    network_mode: host

  gotify:
    image: cthit/gotify
    environment:
      GOTIFY_PRE-SHARED-KEY: "123abc"
      GOTIFY_MOCK-MODE: "true"
      GOTIFY_DEBUG-MODE: "true"
    network_mode: host
