server:
    port: 3001
logging:
    level:
        root: INFO
spring:
    security:
        oauth2:
            client:
                registration:
                    gamma:
                        client-id: "ULISGPUJIK1WK2K8XPQ64NQ8H1ZM8D"
                        client-secret: "VLjfKrWxQpsQm2a7FpIizSexPVr7AZztJhmDBig7vHDaqYkkwEHF4F5ATFZL7KA8EHuMmGvwWm7zhmmColZsipVyans55VhGXUU8xR1iG8BkqcueaX7AXglL6gngEMBC"
                        client-authentication-method: client_secret_basic
                        authorization-grant-type: authorization_code
                        scope: openid,profile,email
                        redirect-uri: http://client:3001/login/oauth2/code/gamma
                        provider: gamma
                        client-name: gamma
                provider:
                    gamma:
                        token-uri: http://gamma:8081/oauth2/token
                        authorization-uri: http://gamma:8081/oauth2/authorize
                        jwk-set-uri: http://gamma:8081/oauth2/jwks
                        user-info-uri: http://gamma:8081/oauth2/userinfo
                        user-name-attribute: name
