server:
    port: 3001
logging:
    level:
        root: INFO
spring:
    security:
        oauth2:
            client:
                registration:
                    gamma:
                        client-id: "MRELEFSLYGYU3AE3BIX1FI4825LULK"
                        client-secret: "aOntr42pGaO3QxK1Ydgn4pCVZAQh463Qc24EKqnU6KGS5lbN4ZY5iAY7noE2uQXnhrTv1jpxPDumI8hteuG78UkLxnf46BLPLLSklw524cI2YLiVmmScW2Ui4A7bjVCj"
                        client-authentication-method: client_secret_basic
                        authorization-grant-type: authorization_code
                        scope: openid,profile,email
                        redirect-uri: http://client:3001/login/oauth2/code/gamma
                        provider: gamma
                        client-name: gamma
                provider:
                    gamma:
                        token-uri: http://gamma:8081/oauth2/token
                        authorization-uri: http://gamma:8081/oauth2/authorize
                        jwk-set-uri: http://gamma:8081/oauth2/jwks
                        user-info-uri: http://gamma:8081/userinfo
                        user-name-attribute: name
