server:
    port: 3001
spring:
    security:
        oauth2:
            client:
                registration:
                    gamma:
                        client-id: test
                        client-secret: secret
                        authorization-grant-type: authorization_code
                        scope: access
                        redirect-uri: http://client:3001/login/oauth2/code/gamma
                        provider: gamma
                provider:
                    gamma:
                        token-uri: http://gamma:8081/api/oauth2/token
                        authorization-uri: http://gamma:8081/api/oauth2/authorize
                        user-info-uri: http://gamma:8081/client/v1/users/me
                        user-name-attribute: nick
                        client-name: gamma
                        authorization-grant-type: authorization_code
