server:
    port: 3001
logging:
    level:
        root: INFO
spring:
    security:
        oauth2:
            client:
                registration:
                    gamma:
                        client-id: test
                        client-secret: secret
                        client-authentication-method: client_secret_basic
                        authorization-grant-type: authorization_code
                        scope: openid,profile,email
                        redirect-uri: http://client:3001/login/oauth2/code/gamma
                        provider: gamma
                        client-name: gamma
                provider:
                    gamma:
                        token-uri: http://gamma:8081/api/oauth2/token
                        authorization-uri: http://gamma:8081/api/oauth2/authorize
                        jwk-set-uri: http://gamma:8081/api/oauth2/jwks
                        user-info-uri: http://gamma:8081/api/userinfo
                        user-name-attribute: name
