spring:
  datasource:
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:postgres}
  flyway:
    baseline-on-migrate: true
    locations:
      classpath:/db/migration
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  data:
    redis:
      host: ${REDIS_HOST:0.0.0.0}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:6379}
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  session:
    store-type: redis

server:
  port: ${SERVER_PORT:9090}
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:43200}

logging:
  file:
    name: ${LOGGING_FILE:production.log}
  level:
    root: ${ROOT_DEBUG_LEVEL:WARN}

application:
  base-uri: ${BACKEND_URI:http://gamma:9090}
  production: ${PRODUCTION:true}
  cookie:
    domain: ${COOKIE_DOMAIN:https://gamma.chalmers.it}
    path: ${COOKIE_PATH:/}
    validity-time: 31536000 # One year
  frontend-client-details:
    successful-login-uri: ${SUCCESSFUL_LOGIN:http://gamma:8080}
  mocking: ${IS_MOCKING:false}
  gotify:
    key: ${GOTIFY_KEY:""}
    url: ${GOTIFY_URL:""}
  allowed-origin: ${CORS_ALLOWED_ORIGIN:https://gamma.chalmers.it}

