version: "3"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'

  redis:
    image: redis:5.0
    ports:
      - '6379:6379'

  gotify:
    image: cthit/gotify
    environment:
      GOTIFY_PRE-SHARED-KEY: "123abc"
      GOTIFY_MOCK-MODE: "true"
      GOTIFY_DEBUG-MODE: "true"
    ports:
      - '8080:8080'