spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:example}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  data:
    redis:
      host: ${REDIS_HOST:0.0.0.0}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

server:
  port: ${SERVER_PORT:8081}
  error:
    whitelabel:
      enabled: true
    path: /error
  servlet:
    context-path: /api

logging:
  level:
    root: ${ROOT_DEBUG_LEVEL:DEBUG}

application:
  base-uri: http://gamma:8081
  production: false
  files:
    path: uploads/
  cookie:
    domain: ${COOKIE_DOMAIN:gamma}
    path: ${COOKIE_PATH:/}
    validity-time: 31536000
  mocking: ${IS_MOCKING:true}
  admin-setup: ${ADMIN_SETUP:true}
  default-oauth2-client:
    client-name: ${DEFAULT_CLIENT_NAME:test-client}
    client-id: ${DEFAULT_CLIENT_ID:test}
    client-secret: ${DEFAULT_CLIENT_SECRET:secret}
    redirect-url: ${DEFAULT_REDIRECT_URL:http://client:3001/login/oauth2/code/gamma}
    api-key: ${DEFAULT_API_KEY:test-api-key-secret-code}
    scopes: ${DEFAULT_SCOPES:profile,email}
  frontend-client-details:
    successful-login-uri: ${SUCCESSFUL_LOGIN:http://gamma:3000}
  gotify:
    key: "123abc"                  # This is not needed, but application crashes since it looks for these values.
    url: "localhost:7000"
  allowed-origin: ${CORS_ALLOWED_ORIGIN:http://gamma:3000}
